2018-07-24 23:47:11.833 [error] <0.1516.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.1521.0> exit with reason normal in context child_terminated
2018-07-24 23:47:11.984 [error] <0.1581.0>@Elixir.Genstages.Application:scenario_workers:29 CRASH REPORT Process <0.1581.0> with 0 neighbours exited with reason: no function clause matching 'Elixir.Genstages.Application':scenario_workers(<<>>) line 29 in application_master:init/4 line 134
2018-07-24 23:47:26.066 [error] <0.331.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.336.0> exit with reason normal in context child_terminated
2018-07-24 23:47:40.768 [error] <0.206.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.211.0> exit with reason normal in context child_terminated
2018-07-24 23:57:25.224 [error] <0.343.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.348.0> exit with reason normal in context child_terminated
