2018-07-25 00:05:52.995 [error] <0.207.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.212.0> exit with reason normal in context child_terminated
2018-07-25 00:05:53.254 [error] <0.285.0> Supervisor 'Elixir.Genstages.RabbitMQ.Supervisor' had child 'Elixir.Genstages.RabbitMQ.Publisher' started with 'Elixir.Genstages.RabbitMQ.Publisher':start_link() at undefined exit with reason {'EXIT',{undef,[{'Elixir.Genstages.RabbitMQ.Publisher',start_link,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2018-07-25 00:05:53.255 [error] <0.274.0> Supervisor 'Elixir.Genstages.Supervisor' had child 'Elixir.Genstages.RabbitMQ.Supervisor' started with 'Elixir.Genstages.RabbitMQ.Supervisor':start_link() at undefined exit with reason {shutdown,{failed_to_start_child,'Elixir.Genstages.RabbitMQ.Publisher',{'EXIT',{undef,[{'Elixir.Genstages.RabbitMQ.Publisher',start_link,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,...},...]}]}}}} in context start_error
2018-07-25 00:05:53.255 [error] <0.272.0> CRASH REPORT Process <0.272.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Genstages.RabbitMQ.Supervisor',{shutdown,{failed_to_start_child,'Elixir.Genstages.RabbitMQ.Publisher',{'EXIT',{undef,[{'Elixir.Genstages.RabbitMQ.Publisher',start_link,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,...},...]}}}}}},...} in application_master:init/4 line 134
2018-07-25 00:06:23.786 [error] <0.198.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.203.0> exit with reason normal in context child_terminated
2018-07-25 00:06:23.982 [error] <0.276.0> Supervisor 'Elixir.Genstages.RabbitMQ.Supervisor' had child 'Elixir.Genstages.RabbitMQ.Publisher' started with 'Elixir.Genstages.RabbitMQ.Publisher':start_link() at undefined exit with reason {'EXIT',{undef,[{'Elixir.Genstages.RabbitMQ.Publisher',start_link,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in context start_error
2018-07-25 00:06:23.982 [error] <0.265.0> Supervisor 'Elixir.Genstages.Supervisor' had child 'Elixir.Genstages.RabbitMQ.Supervisor' started with 'Elixir.Genstages.RabbitMQ.Supervisor':start_link() at undefined exit with reason {shutdown,{failed_to_start_child,'Elixir.Genstages.RabbitMQ.Publisher',{'EXIT',{undef,[{'Elixir.Genstages.RabbitMQ.Publisher',start_link,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,...},...]}]}}}} in context start_error
2018-07-25 00:06:23.983 [error] <0.263.0> CRASH REPORT Process <0.263.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Genstages.RabbitMQ.Supervisor',{shutdown,{failed_to_start_child,'Elixir.Genstages.RabbitMQ.Publisher',{'EXIT',{undef,[{'Elixir.Genstages.RabbitMQ.Publisher',start_link,[],[]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,...},...]}}}}}},...} in application_master:init/4 line 134
2018-07-25 00:06:42.758 [error] <0.206.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.211.0> exit with reason normal in context child_terminated
2018-07-25 00:07:32.178 [error] <0.297.0>@gen_server:call gen_server 'Elixir.Genstages.RabbitMQ.Client' terminated with reason: no such process or port in call to gen_server:call(<0.300.0>, {call,{'basic.get',0,<<"genstages">>,false},none,<0.297.0>}, 60000) in gen_server:call/3 line 214
2018-07-25 00:07:32.178 [error] <0.297.0>@gen_server:call CRASH REPORT Process 'Elixir.Genstages.RabbitMQ.Client' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.300.0>, {call,{'basic.get',0,<<"genstages">>,false},none,<0.297.0>}, 60000) in gen_server:call/3 line 214
2018-07-25 00:07:32.178 [error] <0.284.0>@gen_server:call Supervisor 'Elixir.Genstages.RabbitMQ.Supervisor' had child 'Elixir.Genstages.RabbitMQ.Client' started with 'Elixir.Genstages.RabbitMQ.Client':start_link() at <0.297.0> exit with reason no such process or port in call to gen_server:call(<0.300.0>, {call,{'basic.get',0,<<"genstages">>,false},none,<0.297.0>}, 60000) in context child_terminated
2018-07-25 00:07:44.898 [error] <0.311.0> gen_server 'Elixir.Genstages.RabbitMQ.Client' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'genstages' in vhost '/'">>}},{gen_server,call,[<0.314.0>,{call,{'basic.get',0,<<"genstages">>,false},none,<0.311.0>},60000]}} in gen_server:call/3 line 214
2018-07-25 00:07:44.898 [error] <0.311.0> CRASH REPORT Process 'Elixir.Genstages.RabbitMQ.Client' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'genstages' in vhost '/'">>}},{gen_server,call,[<0.314.0>,{call,{'basic.get',0,<<"genstages">>,false},none,<0.311.0>},60000]}} in gen_server:call/3 line 214
2018-07-25 00:07:44.899 [error] <0.284.0> Supervisor 'Elixir.Genstages.RabbitMQ.Supervisor' had child 'Elixir.Genstages.RabbitMQ.Client' started with 'Elixir.Genstages.RabbitMQ.Client':start_link() at <0.311.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'genstages' in vhost '/'">>}},{gen_server,call,[<0.314.0>,{call,{'basic.get',0,<<"genstages">>,false},none,<0.311.0>},60000]}} in context child_terminated
2018-07-25 00:09:32.044 [error] <0.317.0> gen_server 'Elixir.Genstages.RabbitMQ.Client' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'genstages' in vhost '/'">>}},{gen_server,call,[<0.320.0>,{call,{'basic.get',0,<<"genstages">>,false},none,<0.317.0>},60000]}} in gen_server:call/3 line 214
2018-07-25 00:09:32.046 [error] <0.317.0> CRASH REPORT Process 'Elixir.Genstages.RabbitMQ.Client' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'genstages' in vhost '/'">>}},{gen_server,call,[<0.320.0>,{call,{'basic.get',0,<<"genstages">>,false},none,<0.317.0>},60000]}} in gen_server:call/3 line 214
2018-07-25 00:09:32.048 [error] <0.284.0> Supervisor 'Elixir.Genstages.RabbitMQ.Supervisor' had child 'Elixir.Genstages.RabbitMQ.Client' started with 'Elixir.Genstages.RabbitMQ.Client':start_link() at <0.317.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'genstages' in vhost '/'">>}},{gen_server,call,[<0.320.0>,{call,{'basic.get',0,<<"genstages">>,false},none,<0.317.0>},60000]}} in context child_terminated
2018-07-25 00:09:37.498 [error] <0.324.0>@gen_server:call gen_server 'Elixir.Genstages.RabbitMQ.Client' terminated with reason: no such process or port in call to gen_server:call(<0.327.0>, {call,{'basic.get',0,<<"genstages">>,false},none,<0.324.0>}, 60000) in gen_server:call/3 line 214
2018-07-25 00:09:37.498 [error] <0.324.0>@gen_server:call CRASH REPORT Process 'Elixir.Genstages.RabbitMQ.Client' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.327.0>, {call,{'basic.get',0,<<"genstages">>,false},none,<0.324.0>}, 60000) in gen_server:call/3 line 214
2018-07-25 00:09:37.499 [error] <0.284.0>@gen_server:call Supervisor 'Elixir.Genstages.RabbitMQ.Supervisor' had child 'Elixir.Genstages.RabbitMQ.Client' started with 'Elixir.Genstages.RabbitMQ.Client':start_link() at <0.324.0> exit with reason no such process or port in call to gen_server:call(<0.327.0>, {call,{'basic.get',0,<<"genstages">>,false},none,<0.324.0>}, 60000) in context child_terminated
2018-07-25 00:13:14.777 [error] <0.330.0>@gen_server:call gen_server 'Elixir.Genstages.RabbitMQ.Client' terminated with reason: no such process or port in call to gen_server:call(<0.334.0>, {call,{'basic.get',0,<<"genstages">>,false},none,<0.330.0>}, 60000) in gen_server:call/3 line 214
2018-07-25 00:13:14.783 [error] <0.330.0>@gen_server:call CRASH REPORT Process 'Elixir.Genstages.RabbitMQ.Client' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.334.0>, {call,{'basic.get',0,<<"genstages">>,false},none,<0.330.0>}, 60000) in gen_server:call/3 line 214
2018-07-25 00:13:14.785 [error] <0.284.0>@gen_server:call Supervisor 'Elixir.Genstages.RabbitMQ.Supervisor' had child 'Elixir.Genstages.RabbitMQ.Client' started with 'Elixir.Genstages.RabbitMQ.Client':start_link() at <0.330.0> exit with reason no such process or port in call to gen_server:call(<0.334.0>, {call,{'basic.get',0,<<"genstages">>,false},none,<0.330.0>}, 60000) in context child_terminated
2018-07-25 00:13:23.156 [error] <0.340.0> gen_server 'Elixir.Genstages.RabbitMQ.Client' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'genstages' in vhost '/'">>}},{gen_server,call,[<0.343.0>,{call,{'basic.get',0,<<"genstages">>,false},none,<0.340.0>},60000]}} in gen_server:call/3 line 214
2018-07-25 00:13:23.157 [error] <0.340.0> CRASH REPORT Process 'Elixir.Genstages.RabbitMQ.Client' with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'genstages' in vhost '/'">>}},{gen_server,call,[<0.343.0>,{call,{'basic.get',0,<<"genstages">>,false},none,<0.340.0>},60000]}} in gen_server:call/3 line 214
2018-07-25 00:13:23.158 [error] <0.284.0> Supervisor 'Elixir.Genstages.RabbitMQ.Supervisor' had child 'Elixir.Genstages.RabbitMQ.Client' started with 'Elixir.Genstages.RabbitMQ.Client':start_link() at <0.340.0> exit with reason {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'genstages' in vhost '/'">>}},{gen_server,call,[<0.343.0>,{call,{'basic.get',0,<<"genstages">>,false},none,<0.340.0>},60000]}} in context child_terminated
2018-07-25 00:22:53.434 [error] <0.212.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.217.0> exit with reason normal in context child_terminated
2018-07-25 00:23:25.624 [error] <0.307.0> gen_server 'Elixir.Genstages.RabbitMQ.Client' terminated with reason: bad return value: {reply,{ok,<<"\"WOW1\"">>,#{app_id => undefined,cluster_id => undefined,content_encoding => undefined,content_type => undefined,correlation_id => undefined,delivery_tag => 2,exchange => <<"genstages_exchange">>,expiration => undefined,headers => undefined,message_count => 2,message_id => undefined,persistent => false,priority => undefined,redelivered => false,reply_to => undefined,routing_key => <<>>,timestamp => undefined,type => undefined,user_id => undefined}},#{'__struct__' => 'Elixir.AMQP.Channel',...}}
2018-07-25 00:23:25.624 [error] <0.307.0>@gen_server:handle_common_reply:730 CRASH REPORT Process 'Elixir.Genstages.RabbitMQ.Client' with 0 neighbours exited with reason: bad return value: {reply,{ok,<<"\"WOW1\"">>,#{app_id => undefined,cluster_id => undefined,content_encoding => undefined,content_type => undefined,correlation_id => undefined,delivery_tag => 2,exchange => <<"genstages_exchange">>,expiration => undefined,headers => undefined,message_count => 2,message_id => undefined,persistent => false,priority => undefined,redelivered => false,reply_to => undefined,routing_key => <<>>,timestamp => undefined,type => undefined,user_id => undefined}},#{'__struct__' => 'Elixir.AMQP.Channel',...}} in gen_server:handle_common_reply/8 line 730
2018-07-25 00:23:25.626 [error] <0.290.0> Supervisor 'Elixir.Genstages.RabbitMQ.Supervisor' had child 'Elixir.Genstages.RabbitMQ.Client' started with 'Elixir.Genstages.RabbitMQ.Client':start_link() at <0.307.0> exit with reason bad return value: {reply,{ok,<<"\"WOW1\"">>,#{app_id => undefined,cluster_id => undefined,content_encoding => undefined,content_type => undefined,correlation_id => undefined,delivery_tag => 2,exchange => <<"genstages_exchange">>,expiration => undefined,headers => undefined,message_count => 2,message_id => undefined,persistent => false,priority => undefined,redelivered => false,reply_to => undefined,routing_key => <<>>,timestamp => undefined,type => undefined,user_id => undefined}},#{'__struct__' => 'Elixir.AMQP.Channel',...}} in context child_terminated
2018-07-25 00:24:17.275 [error] <0.206.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.211.0> exit with reason normal in context child_terminated
2018-07-25 00:24:33.255 [error] <0.301.0> gen_server 'Elixir.Genstages.RabbitMQ.Client' terminated with reason: bad return value: {reply,<<"\"WOW\"">>,#{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.288.0>},pid => <0.304.0>}}
2018-07-25 00:24:33.255 [error] <0.301.0>@gen_server:handle_common_reply:730 CRASH REPORT Process 'Elixir.Genstages.RabbitMQ.Client' with 0 neighbours exited with reason: bad return value: {reply,<<"\"WOW\"">>,#{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.288.0>},pid => <0.304.0>}} in gen_server:handle_common_reply/8 line 730
2018-07-25 00:24:33.255 [error] <0.284.0> Supervisor 'Elixir.Genstages.RabbitMQ.Supervisor' had child 'Elixir.Genstages.RabbitMQ.Client' started with 'Elixir.Genstages.RabbitMQ.Client':start_link() at <0.301.0> exit with reason bad return value: {reply,<<"\"WOW\"">>,#{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.288.0>},pid => <0.304.0>}} in context child_terminated
2018-07-25 00:25:02.948 [error] <0.206.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.211.0> exit with reason normal in context child_terminated
2018-07-25 00:25:11.797 [error] <0.301.0> gen_server 'Elixir.Genstages.RabbitMQ.Client' terminated with reason: bad return value: {reply,<<"\"WOW\"">>,#{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.288.0>},pid => <0.304.0>}}
2018-07-25 00:25:11.797 [error] <0.301.0>@gen_server:handle_common_reply:730 CRASH REPORT Process 'Elixir.Genstages.RabbitMQ.Client' with 0 neighbours exited with reason: bad return value: {reply,<<"\"WOW\"">>,#{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.288.0>},pid => <0.304.0>}} in gen_server:handle_common_reply/8 line 730
2018-07-25 00:25:11.797 [error] <0.284.0> Supervisor 'Elixir.Genstages.RabbitMQ.Supervisor' had child 'Elixir.Genstages.RabbitMQ.Client' started with 'Elixir.Genstages.RabbitMQ.Client':start_link() at <0.301.0> exit with reason bad return value: {reply,<<"\"WOW\"">>,#{'__struct__' => 'Elixir.AMQP.Channel',conn => #{'__struct__' => 'Elixir.AMQP.Connection',pid => <0.288.0>},pid => <0.304.0>}} in context child_terminated
2018-07-25 00:26:04.996 [error] <0.206.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.211.0> exit with reason normal in context child_terminated
2018-07-25 00:27:32.852 [error] <0.206.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.211.0> exit with reason normal in context child_terminated
2018-07-25 00:27:49.875 [error] <0.301.0>@Elixir.Genstages.RabbitMQ.Client:handle_call:26 gen_server 'Elixir.Genstages.RabbitMQ.Client' terminated with reason: no match of right hand value {empty,#{cluster_id => <<>>}} in 'Elixir.Genstages.RabbitMQ.Client':handle_call/3 line 26
2018-07-25 00:27:49.876 [error] <0.301.0>@Elixir.Genstages.RabbitMQ.Client:handle_call:26 CRASH REPORT Process 'Elixir.Genstages.RabbitMQ.Client' with 0 neighbours crashed with reason: no match of right hand value {empty,#{cluster_id => <<>>}} in 'Elixir.Genstages.RabbitMQ.Client':handle_call/3 line 26
2018-07-25 00:27:49.876 [error] <0.284.0>@Elixir.Genstages.RabbitMQ.Client:handle_call:26 Supervisor 'Elixir.Genstages.RabbitMQ.Supervisor' had child 'Elixir.Genstages.RabbitMQ.Client' started with 'Elixir.Genstages.RabbitMQ.Client':start_link() at <0.301.0> exit with reason no match of right hand value {empty,#{cluster_id => <<>>}} in 'Elixir.Genstages.RabbitMQ.Client':handle_call/3 line 26 in context child_terminated
2018-07-25 00:27:50.908 [error] <0.314.0>@Elixir.Genstages.RabbitMQ.Client:handle_call:26 gen_server 'Elixir.Genstages.RabbitMQ.Client' terminated with reason: no match of right hand value {empty,#{cluster_id => <<>>}} in 'Elixir.Genstages.RabbitMQ.Client':handle_call/3 line 26
2018-07-25 00:27:50.909 [error] <0.314.0>@Elixir.Genstages.RabbitMQ.Client:handle_call:26 CRASH REPORT Process 'Elixir.Genstages.RabbitMQ.Client' with 0 neighbours crashed with reason: no match of right hand value {empty,#{cluster_id => <<>>}} in 'Elixir.Genstages.RabbitMQ.Client':handle_call/3 line 26
2018-07-25 00:27:50.910 [error] <0.284.0>@Elixir.Genstages.RabbitMQ.Client:handle_call:26 Supervisor 'Elixir.Genstages.RabbitMQ.Supervisor' had child 'Elixir.Genstages.RabbitMQ.Client' started with 'Elixir.Genstages.RabbitMQ.Client':start_link() at <0.314.0> exit with reason no match of right hand value {empty,#{cluster_id => <<>>}} in 'Elixir.Genstages.RabbitMQ.Client':handle_call/3 line 26 in context child_terminated
2018-07-25 00:27:51.464 [error] <0.320.0>@Elixir.Genstages.RabbitMQ.Client:handle_call:26 gen_server 'Elixir.Genstages.RabbitMQ.Client' terminated with reason: no match of right hand value {empty,#{cluster_id => <<>>}} in 'Elixir.Genstages.RabbitMQ.Client':handle_call/3 line 26
2018-07-25 00:27:51.464 [error] <0.320.0>@Elixir.Genstages.RabbitMQ.Client:handle_call:26 CRASH REPORT Process 'Elixir.Genstages.RabbitMQ.Client' with 0 neighbours crashed with reason: no match of right hand value {empty,#{cluster_id => <<>>}} in 'Elixir.Genstages.RabbitMQ.Client':handle_call/3 line 26
2018-07-25 00:27:51.464 [error] <0.284.0>@Elixir.Genstages.RabbitMQ.Client:handle_call:26 Supervisor 'Elixir.Genstages.RabbitMQ.Supervisor' had child 'Elixir.Genstages.RabbitMQ.Client' started with 'Elixir.Genstages.RabbitMQ.Client':start_link() at <0.320.0> exit with reason no match of right hand value {empty,#{cluster_id => <<>>}} in 'Elixir.Genstages.RabbitMQ.Client':handle_call/3 line 26 in context child_terminated
2018-07-25 00:27:51.956 [error] <0.326.0>@Elixir.Genstages.RabbitMQ.Client:handle_call:26 gen_server 'Elixir.Genstages.RabbitMQ.Client' terminated with reason: no match of right hand value {empty,#{cluster_id => <<>>}} in 'Elixir.Genstages.RabbitMQ.Client':handle_call/3 line 26
2018-07-25 00:27:51.957 [error] <0.326.0>@Elixir.Genstages.RabbitMQ.Client:handle_call:26 CRASH REPORT Process 'Elixir.Genstages.RabbitMQ.Client' with 0 neighbours crashed with reason: no match of right hand value {empty,#{cluster_id => <<>>}} in 'Elixir.Genstages.RabbitMQ.Client':handle_call/3 line 26
2018-07-25 00:27:51.957 [error] <0.284.0>@Elixir.Genstages.RabbitMQ.Client:handle_call:26 Supervisor 'Elixir.Genstages.RabbitMQ.Supervisor' had child 'Elixir.Genstages.RabbitMQ.Client' started with 'Elixir.Genstages.RabbitMQ.Client':start_link() at <0.326.0> exit with reason no match of right hand value {empty,#{cluster_id => <<>>}} in 'Elixir.Genstages.RabbitMQ.Client':handle_call/3 line 26 in context child_terminated
2018-07-25 00:27:51.957 [error] <0.284.0> Supervisor 'Elixir.Genstages.RabbitMQ.Supervisor' had child 'Elixir.Genstages.RabbitMQ.Client' started with 'Elixir.Genstages.RabbitMQ.Client':start_link() at <0.326.0> exit with reason reached_max_restart_intensity in context shutdown
2018-07-25 00:27:51.958 [error] <0.273.0> Supervisor 'Elixir.Genstages.Supervisor' had child 'Elixir.Genstages.RabbitMQ.Supervisor' started with 'Elixir.Genstages.RabbitMQ.Supervisor':start_link() at <0.284.0> exit with reason shutdown in context child_terminated
2018-07-25 00:27:52.434 [error] <0.348.0>@Elixir.Genstages.RabbitMQ.Client:handle_call:26 gen_server 'Elixir.Genstages.RabbitMQ.Client' terminated with reason: no match of right hand value {empty,#{cluster_id => <<>>}} in 'Elixir.Genstages.RabbitMQ.Client':handle_call/3 line 26
2018-07-25 00:27:52.435 [error] <0.348.0>@Elixir.Genstages.RabbitMQ.Client:handle_call:26 CRASH REPORT Process 'Elixir.Genstages.RabbitMQ.Client' with 0 neighbours crashed with reason: no match of right hand value {empty,#{cluster_id => <<>>}} in 'Elixir.Genstages.RabbitMQ.Client':handle_call/3 line 26
2018-07-25 00:27:52.439 [error] <0.332.0>@Elixir.Genstages.RabbitMQ.Client:handle_call:26 Supervisor 'Elixir.Genstages.RabbitMQ.Supervisor' had child 'Elixir.Genstages.RabbitMQ.Client' started with 'Elixir.Genstages.RabbitMQ.Client':start_link() at <0.348.0> exit with reason no match of right hand value {empty,#{cluster_id => <<>>}} in 'Elixir.Genstages.RabbitMQ.Client':handle_call/3 line 26 in context child_terminated
2018-07-25 00:27:53.010 [error] <0.353.0>@Elixir.Genstages.RabbitMQ.Client:handle_call:26 gen_server 'Elixir.Genstages.RabbitMQ.Client' terminated with reason: no match of right hand value {empty,#{cluster_id => <<>>}} in 'Elixir.Genstages.RabbitMQ.Client':handle_call/3 line 26
2018-07-25 00:27:53.011 [error] <0.353.0>@Elixir.Genstages.RabbitMQ.Client:handle_call:26 CRASH REPORT Process 'Elixir.Genstages.RabbitMQ.Client' with 0 neighbours crashed with reason: no match of right hand value {empty,#{cluster_id => <<>>}} in 'Elixir.Genstages.RabbitMQ.Client':handle_call/3 line 26
2018-07-25 00:27:53.012 [error] <0.332.0>@Elixir.Genstages.RabbitMQ.Client:handle_call:26 Supervisor 'Elixir.Genstages.RabbitMQ.Supervisor' had child 'Elixir.Genstages.RabbitMQ.Client' started with 'Elixir.Genstages.RabbitMQ.Client':start_link() at <0.353.0> exit with reason no match of right hand value {empty,#{cluster_id => <<>>}} in 'Elixir.Genstages.RabbitMQ.Client':handle_call/3 line 26 in context child_terminated
2018-07-25 00:29:26.664 [error] <0.206.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.211.0> exit with reason normal in context child_terminated
2018-07-25 00:30:55.490 [error] <0.198.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.203.0> exit with reason normal in context child_terminated
2018-07-25 00:34:02.778 [error] <0.206.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.211.0> exit with reason normal in context child_terminated
2018-07-25 00:34:21.258 [error] <0.198.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.203.0> exit with reason normal in context child_terminated
2018-07-25 00:36:35.510 [error] <0.207.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.212.0> exit with reason normal in context child_terminated
2018-07-25 00:38:25.066 [error] <0.206.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.211.0> exit with reason normal in context child_terminated
2018-07-25 00:44:17.687 [error] <0.343.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.348.0> exit with reason normal in context child_terminated
2018-07-25 00:44:17.884 [error] <0.444.0>@gen_server:init_it:349 CRASH REPORT Process <0.444.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:init_it/6 line 349
2018-07-25 00:44:17.884 [error] <0.410.0> Supervisor 'Elixir.Genstages.Supervisor' had child 'Elixir.Genstages.Samples.ConsumerSupervisor' started with 'Elixir.Genstages.Samples.ConsumerSupervisor':start_link() at undefined exit with reason noproc in context start_error
2018-07-25 00:44:17.884 [error] <0.408.0> CRASH REPORT Process <0.408.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Genstages.Samples.ConsumerSupervisor',noproc}},{'Elixir.Genstages.Application',start,[normal,[]]}} in application_master:init/4 line 134
2018-07-25 00:44:42.359 [error] <0.343.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.348.0> exit with reason normal in context child_terminated
2018-07-25 00:44:49.618 [error] <0.343.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.348.0> exit with reason normal in context child_terminated
2018-07-25 00:44:49.863 [error] <0.444.0>@gen_server:init_it:349 CRASH REPORT Process <0.444.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:init_it/6 line 349
2018-07-25 00:44:49.863 [error] <0.410.0> Supervisor 'Elixir.Genstages.Supervisor' had child 'Elixir.Genstages.Samples.ConsumerSupervisor' started with 'Elixir.Genstages.Samples.ConsumerSupervisor':start_link() at undefined exit with reason noproc in context start_error
2018-07-25 00:44:49.863 [error] <0.408.0> CRASH REPORT Process <0.408.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Genstages.Samples.ConsumerSupervisor',noproc}},{'Elixir.Genstages.Application',start,[normal,[]]}} in application_master:init/4 line 134
2018-07-25 00:45:45.497 [error] <0.206.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.211.0> exit with reason normal in context child_terminated
2018-07-25 00:45:45.728 [error] <0.307.0>@gen_server:init_it:349 CRASH REPORT Process <0.307.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:init_it/6 line 349
2018-07-25 00:45:45.728 [error] <0.273.0> Supervisor 'Elixir.Genstages.Supervisor' had child 'Elixir.Genstages.Samples.ConsumerSupervisor' started with 'Elixir.Genstages.Samples.ConsumerSupervisor':start_link() at undefined exit with reason noproc in context start_error
2018-07-25 00:45:45.728 [error] <0.271.0> CRASH REPORT Process <0.271.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Genstages.Samples.ConsumerSupervisor',noproc}},{'Elixir.Genstages.Application',start,[normal,[]]}} in application_master:init/4 line 134
2018-07-25 00:47:15.073 [error] <0.206.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.211.0> exit with reason normal in context child_terminated
2018-07-25 00:47:15.256 [error] <0.307.0>@gen_server:init_it:349 CRASH REPORT Process <0.307.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:init_it/6 line 349
2018-07-25 00:47:15.256 [error] <0.273.0> Supervisor 'Elixir.Genstages.Supervisor' had child 'Elixir.Genstages.Samples.ConsumerSupervisor' started with 'Elixir.Genstages.Samples.ConsumerSupervisor':start_link() at undefined exit with reason noproc in context start_error
2018-07-25 00:47:15.257 [error] <0.271.0> CRASH REPORT Process <0.271.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Genstages.Samples.ConsumerSupervisor',noproc}},{'Elixir.Genstages.Application',start,[normal,[]]}} in application_master:init/4 line 134
2018-07-25 00:47:31.908 [error] <0.206.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.211.0> exit with reason normal in context child_terminated
2018-07-25 00:49:45.508 [error] <0.343.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.348.0> exit with reason normal in context child_terminated
2018-07-25 00:50:19.181 [error] <0.343.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.348.0> exit with reason normal in context child_terminated
2018-07-25 00:50:50.485 [error] <0.206.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.211.0> exit with reason normal in context child_terminated
2018-07-25 00:50:58.065 [error] <0.343.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.348.0> exit with reason normal in context child_terminated
2018-07-25 00:50:58.346 [error] <0.444.0>@gen_server:init_it:349 CRASH REPORT Process <0.444.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:init_it/6 line 349
2018-07-25 00:50:58.346 [error] <0.410.0> Supervisor 'Elixir.Genstages.Supervisor' had child 'Elixir.Genstages.Samples.ConsumerSupervisor' started with 'Elixir.Genstages.Samples.ConsumerSupervisor':start_link() at undefined exit with reason noproc in context start_error
2018-07-25 00:50:58.347 [error] <0.408.0> CRASH REPORT Process <0.408.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Genstages.Samples.ConsumerSupervisor',noproc}},{'Elixir.Genstages.Application',start,[normal,[]]}} in application_master:init/4 line 134
2018-07-25 00:52:47.907 [error] <0.206.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.211.0> exit with reason normal in context child_terminated
2018-07-25 00:52:48.094 [error] <0.307.0>@gen_server:init_it:349 CRASH REPORT Process <0.307.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:init_it/6 line 349
2018-07-25 00:52:48.094 [error] <0.273.0> Supervisor 'Elixir.Genstages.Supervisor' had child 'Elixir.Genstages.Samples.ConsumerSupervisor' started with 'Elixir.Genstages.Samples.ConsumerSupervisor':start_link() at undefined exit with reason noproc in context start_error
2018-07-25 00:52:48.095 [error] <0.271.0> CRASH REPORT Process <0.271.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Genstages.Samples.ConsumerSupervisor',noproc}},{'Elixir.Genstages.Application',start,[normal,[]]}} in application_master:init/4 line 134
2018-07-25 00:53:41.756 [error] <0.206.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.211.0> exit with reason normal in context child_terminated
2018-07-25 00:55:10.036 [error] <0.206.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.211.0> exit with reason normal in context child_terminated
2018-07-25 00:55:26.860 [error] <0.198.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.203.0> exit with reason normal in context child_terminated
2018-07-25 00:56:42.130 [error] <0.302.0>@gen_server:init_it:349 CRASH REPORT Process <0.302.0> with 1 neighbours exited with reason: bad return value: {ok,[{'Elixir.Genstages.Samples.Consumer',{'Elixir.Genstages.Samples.Consumer',start_link,[]},temporary,5000,worker,['Elixir.Genstages.Samples.Consumer']}],[{strategy,one_for_one},{subscribe_to,[{'Elixir.Genstages.Samples.Producer',[{min_demand,1},{max_demand,10}]}]}]} in gen_server:init_it/6 line 349
2018-07-25 00:56:48.993 [error] <0.305.0>@gen_server:init_it:349 CRASH REPORT Process <0.305.0> with 1 neighbours exited with reason: bad return value: {ok,[{'Elixir.Genstages.Samples.Consumer',{'Elixir.Genstages.Samples.Consumer',start_link,[]},temporary,5000,worker,['Elixir.Genstages.Samples.Consumer']}],[{strategy,one_for_one},{subscribe_to,[{'Elixir.Genstages.Samples.Producer',[{min_demand,1},{max_demand,10}]}]}]} in gen_server:init_it/6 line 349
2018-07-25 00:56:53.461 [error] <0.308.0>@gen_server:init_it:349 CRASH REPORT Process <0.308.0> with 1 neighbours exited with reason: bad return value: {ok,[{'Elixir.Genstages.Samples.Consumer',{'Elixir.Genstages.Samples.Consumer',start_link,[]},temporary,5000,worker,['Elixir.Genstages.Samples.Consumer']}],[{strategy,one_for_one},{subscribe_to,[{'Elixir.Genstages.Samples.Producer',[{min_demand,1},{max_demand,10}]}]}]} in gen_server:init_it/6 line 349
2018-07-25 00:56:57.029 [error] <0.311.0>@gen_server:init_it:349 CRASH REPORT Process <0.311.0> with 1 neighbours exited with reason: bad return value: {ok,[{'Elixir.Genstages.Samples.Consumer',{'Elixir.Genstages.Samples.Consumer',start_link,[]},temporary,5000,worker,['Elixir.Genstages.Samples.Consumer']}],[{strategy,one_for_one},{subscribe_to,[{'Elixir.Genstages.Samples.Producer',[{min_demand,1},{max_demand,10}]}]}]} in gen_server:init_it/6 line 349
2018-07-25 00:58:12.330 [error] <0.315.0>@gen_server:init_it:349 CRASH REPORT Process <0.315.0> with 1 neighbours exited with reason: bad return value: {ok,[{'Elixir.Genstages.Samples.Consumer',{'Elixir.Genstages.Samples.Consumer',start_link,[]},temporary,5000,worker,['Elixir.Genstages.Samples.Consumer']}],[{strategy,one_for_one},{subscribe_to,[{'Elixir.Genstages.Samples.Producer',[{min_demand,1},{max_demand,10}]}]}]} in gen_server:init_it/6 line 349
2018-07-25 00:58:14.047 [error] <0.318.0>@gen_server:init_it:349 CRASH REPORT Process <0.318.0> with 1 neighbours exited with reason: bad return value: {ok,[{'Elixir.Genstages.Samples.Consumer',{'Elixir.Genstages.Samples.Consumer',start_link,[]},temporary,5000,worker,['Elixir.Genstages.Samples.Consumer']}],[{strategy,one_for_one},{subscribe_to,[{'Elixir.Genstages.Samples.Producer',[{min_demand,1},{max_demand,10}]}]}]} in gen_server:init_it/6 line 349
2018-07-25 00:58:37.802 [error] <0.206.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.211.0> exit with reason normal in context child_terminated
2018-07-25 00:58:53.697 [error] <0.206.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.211.0> exit with reason normal in context child_terminated
2018-07-25 00:59:28.725 [error] <0.343.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.348.0> exit with reason normal in context child_terminated
2018-07-25 01:00:30.249 [error] <0.343.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.348.0> exit with reason normal in context child_terminated
